/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, Record<string, any>> = {
  "aodesu": {
    "avatar": {
      name: "avatar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/aodesu/ui/avatar.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/aodesu/ui/avatar.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/aodesu/ui/button.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/aodesu/ui/button.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "avatar-demo": {
      name: "avatar-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["avatar"],
      files: [{
        path: "registry/aodesu/examples/avatar/avatar-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/aodesu/examples/avatar/avatar-demo.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "button-demo": {
      name: "button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/aodesu/examples/button/button-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/aodesu/examples/button/button-demo.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "button-contained": {
      name: "button-contained",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/aodesu/examples/button/button-contained.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/aodesu/examples/button/button-contained.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "button-outlined": {
      name: "button-outlined",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/aodesu/examples/button/button-outlined.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/aodesu/examples/button/button-outlined.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "button-ghost": {
      name: "button-ghost",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/aodesu/examples/button/button-ghost.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/aodesu/examples/button/button-ghost.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "button-text": {
      name: "button-text",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/aodesu/examples/button/button-text.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/aodesu/examples/button/button-text.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "button-colors": {
      name: "button-colors",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/aodesu/examples/button/button-colors.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/aodesu/examples/button/button-colors.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "button-sizes": {
      name: "button-sizes",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/aodesu/examples/button/button-sizes.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/aodesu/examples/button/button-sizes.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "button-with-icon": {
      name: "button-with-icon",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/aodesu/examples/button/button-with-icon.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/aodesu/examples/button/button-with-icon.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "button-icon": {
      name: "button-icon",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/aodesu/examples/button/button-icon.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/aodesu/examples/button/button-icon.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "button-disabled": {
      name: "button-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/aodesu/examples/button/button-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/aodesu/examples/button/button-disabled.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "button-loading": {
      name: "button-loading",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/aodesu/examples/button/button-loading.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/aodesu/examples/button/button-loading.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
  },
}